[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Etherscan API keys for verification
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
